import './globals.css';
import Navbar from '@/components/shared/Navbar';

export const metadata = {
  title: 'My App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>

          <Navbar />
          {children}
      </body>
    </html>
  );
}